#!/bin/bash
all :
	asciidoctor-pdf -a source-highlighter=rouge -a rouge-style=thankful_eyes QRH_SSH_git.adoc
	asciidoctor -a source-highlighter=rouge -a rouge-style=thankful_eyes QRH_SSH_git.adoc
	asciidoctor-pdf -a source-highlighter=rouge -a rouge-style=thankful_eyes QRH_SSH_git.adoc
	asciidoctor-epub3 -a source-highlighter=rouge -a rouge-style=thankful_eyes QRH_SSH_git.adoc
