= Liste de commande de compilation pour la génération de fichier HTML5 / PDF et EPUB3 avec coloration syntaxique

* Génération d'un fichier HTML5 depuis le fichier .adoc :
[source, shell]
----
asciidoctor QRH_BD.adoc
----
    

* Génération d'un fichier PDF avec asciidoctor-pdf :
[source, shell]
----
asciidoctor-pdf QRH_BD.adoc
----

* Génération d'un fichier EPUB3 avec asciidoctor-epub3 :
[source, shell]
----
asciidoctor-epub3 QRH_BD.adoc
----

== Installation des gems ruby nécessaires
Pour avoir de la coloration syntaxique des fragments de code et fichier inclus, il est préférable d'installer les *gems* ruby suivantes :

* asciidoctor-pdf : pour la génération de fichier PDF depuis le document asciidoctor

* asciidoctor-epub3 : pour la génération de fichier EPUB3 depuis le document asciidoctor

Le site https://nextgentips.com/2022/11/17/how-to-install-rails-7-on-manjaro-linux[nextgentips.com] décrit comme installer les gems.
Il faut juste noter qu'il est nécessaire d'ajouter le *path* Ruby pour avoir accès aux gems depuis un terminal
